/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PanelConrtrol;

import Entidades.Provedores;
import Entidades.Usuario;
import Entidades.clientes;
import LogIn.*;
import cjb.ci.Mensaje;
import clases.IMGtabla;
import clases.editTable;
import java.awt.FileDialog;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import metodos.Querys;
import java.sql.Connection;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import metodos.ManipulaDBC;

/**
 *
 * @author Rasteck7
 */
public class PC extends javax.swing.JFrame {
    Usuario mod;
    Connection con;
    clientes cli;
    Provedores prov;
    Querys q = new Querys();
    public static DefaultTableModel atm=new editTable();
    JFileChooser jf;
    /**
     * Creates new form Registro
     */
    public PC() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Registro");
        //Nav.setEnabledAt(4, false);
        ImageIcon icon = new ImageIcon("src/Imagen/LogoMonza.png");
        this.setIconImage(icon.getImage());
        String []titulo=new String[] {"Nombre","Descripcion","PrecioG","precioN","Imagen"};
         
       
    }
    public PC(Usuario mod){
        initComponents();
        this.mod= mod;
        this.setLocationRelativeTo(null);
        this.setTitle("Registro");
        //Nav.setEnabledAt(4, false);
        ImageIcon icon = new ImageIcon("src/Imagen/LogoMonza.png");
        this.setIconImage(icon.getImage());
        if(mod.getTipo()==1){
            
            Nav.setEnabledAt(0, true);
            Nav.setEnabledAt(1, true);
            Nav.setEnabledAt(2, true);
            Nav.setEnabledAt(3, true);
            Nav.setEnabledAt(4, true);
            Nav.setEnabledAt(5, true);
            
        }else if(mod.getTipo()==2){
            Nav.setEnabledAt(0, true);
            Nav.setEnabledAt(1, true);
            Nav.setEnabledAt(2, true);
            Nav.setEnabledAt(3, true);
            Nav.setEnabledAt(4, true);
            Nav.setEnabledAt(5, false);
        }
        
         String []titulo=new String[] {"Modelo","Nombre","Precio","Marca/Provedor","Cantidad","Categoria","Imagen"};
         agenda1.setDefaultRenderer(Object.class,new IMGtabla());
         atm.setColumnIdentifiers(titulo);
         agenda1.setRowHeight(70);
         agenda1.setModel(atm);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLocaleChooser1 = new com.toedter.components.JLocaleChooser();
        jPanel1 = new javax.swing.JPanel();
        Nav = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        Nota = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jTFuser2 = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        Total = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jTFuser1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        NNote = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTFuser = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jComboBox1 = new javax.swing.JComboBox<>();
        Add = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jBGuardar = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        Productos = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ap1 = new javax.swing.JTextField();
        nmo1 = new javax.swing.JTextField();
        am1 = new javax.swing.JTextField();
        name1 = new javax.swing.JTextField();
        email1 = new javax.swing.JTextField();
        nmm1 = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        buscar1 = new javax.swing.JTextField();
        jBGuardar1 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        agenda1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        txtFile = new javax.swing.JTextField();
        Clientes = new javax.swing.JPanel();
        Clean = new javax.swing.JButton();
        buscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTFuser3 = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        agenda = new javax.swing.JTable();
        Entregas = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        buscar2 = new javax.swing.JTextField();
        jScrollPane10 = new javax.swing.JScrollPane();
        jScrollPane11 = new javax.swing.JScrollPane();
        agenda3 = new javax.swing.JTable();
        Minimize1 = new javax.swing.JButton();
        Proveedores = new javax.swing.JPanel();
        Nomprov = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        buscar3 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        dirccprove = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        emailprov = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        telprov = new javax.swing.JTextField();
        jSeparator18 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator19 = new javax.swing.JSeparator();
        mercprov = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane12 = new javax.swing.JScrollPane();
        agenda4 = new javax.swing.JTable();
        Add1 = new javax.swing.JButton();
        Bitacora = new javax.swing.JPanel();
        jScrollPane13 = new javax.swing.JScrollPane();
        agenda5 = new javax.swing.JTable();
        Date1 = new javax.swing.JLabel();
        Minimize2 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Shutdown = new javax.swing.JButton();
        Minimize = new javax.swing.JButton();
        Close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(243, 240, 235));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nav.setBackground(new java.awt.Color(243, 240, 235));
        Nav.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Nav.setToolTipText("");
        Nav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NavMousePressed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(243, 240, 235));

        Nota.setBackground(new java.awt.Color(243, 240, 235));
        Nota.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Nota.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, 100, -1));

        jLabel26.setBackground(new java.awt.Color(235, 235, 235));
        jLabel26.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel26.setText("Fecha de Entrega:");
        Nota.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 420, 120, 20));

        jTFuser2.setBackground(new java.awt.Color(243, 240, 235));
        jTFuser2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTFuser2.setForeground(new java.awt.Color(102, 102, 102));
        jTFuser2.setText("00.00");
        jTFuser2.setBorder(null);
        jTFuser2.setCaretColor(new java.awt.Color(204, 51, 0));
        jTFuser2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTFuser2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFuser2MouseClicked(evt);
            }
        });
        jTFuser2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFuser2ActionPerformed(evt);
            }
        });
        Nota.add(jTFuser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 140, 20));

        jSeparator6.setBackground(new java.awt.Color(235, 235, 235));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        Nota.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 160, 10));

        jLabel25.setBackground(new java.awt.Color(235, 235, 235));
        jLabel25.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel25.setText("Monto Recibido:");
        Nota.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 120, 20));

        jRadioButton2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jRadioButton2.setText("Credito");
        Nota.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 90, -1));

        jRadioButton1.setBackground(new java.awt.Color(243, 240, 235));
        jRadioButton1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jRadioButton1.setText("Contado");
        Nota.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 90, -1));

        Total.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Total.setForeground(new java.awt.Color(102, 102, 102));
        Total.setText("XXXXXX");
        Nota.add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 370, 160, 20));

        jSeparator5.setBackground(new java.awt.Color(235, 235, 235));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        Nota.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 390, 160, 10));

        jLabel24.setBackground(new java.awt.Color(235, 235, 235));
        jLabel24.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel24.setText("Total:");
        Nota.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 370, 40, 20));

        jLabel7.setBackground(new java.awt.Color(235, 235, 235));
        jLabel7.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel7.setText("Cantidad:");
        Nota.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 70, 20));

        jSeparator4.setBackground(new java.awt.Color(235, 235, 235));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        Nota.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 190, 10));

        jTFuser1.setBackground(new java.awt.Color(243, 240, 235));
        jTFuser1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTFuser1.setForeground(new java.awt.Color(102, 102, 102));
        jTFuser1.setText("Nombre del Producto");
        jTFuser1.setBorder(null);
        jTFuser1.setCaretColor(new java.awt.Color(204, 51, 0));
        jTFuser1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTFuser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFuser1MouseClicked(evt);
            }
        });
        Nota.add(jTFuser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 170, 20));

        jLabel6.setBackground(new java.awt.Color(235, 235, 235));
        jLabel6.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel6.setText("Nombre del Producto:");
        Nota.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 160, 20));

        NNote.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        NNote.setText("Numero de Nota:XXXXX");
        Nota.add(NNote, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 180, 40));

        Date.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        Date.setText("Fecha de Compra:");
        Nota.add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 140, 40));

        jLabel5.setBackground(new java.awt.Color(235, 235, 235));
        jLabel5.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel5.setText("Modelo:");
        Nota.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 60, 20));

        jTFuser.setBackground(new java.awt.Color(243, 240, 235));
        jTFuser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTFuser.setForeground(new java.awt.Color(102, 102, 102));
        jTFuser.setText("Ingrese Modelo ");
        jTFuser.setBorder(null);
        jTFuser.setCaretColor(new java.awt.Color(204, 51, 0));
        jTFuser.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTFuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFuserMouseClicked(evt);
            }
        });
        Nota.add(jTFuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 140, 20));

        jSeparator3.setBackground(new java.awt.Color(235, 235, 235));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        Nota.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 160, 10));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Nota.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 100, -1));

        Add.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/add2.png"))); // NOI18N
        Add.setBorder(null);
        Add.setBorderPainted(false);
        Add.setContentAreaFilled(false);
        Add.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Add.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/add1.png"))); // NOI18N
        Add.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/add1.png"))); // NOI18N
        Add.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/add1.png"))); // NOI18N
        Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AddMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                AddMouseReleased(evt);
            }
        });
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        Nota.add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, -1, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "(ID)Modelo", "Nombre del Producto", "cantidad", "Monto por unidad", "Monto subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTable1);

        Nota.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 900, 220));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane7.setViewportView(jTextArea1);

        Nota.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 340, 60));

        jLabel27.setBackground(new java.awt.Color(235, 235, 235));
        jLabel27.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel27.setText("Tipo de Entrega:");
        Nota.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 110, 20));

        jLabel28.setBackground(new java.awt.Color(235, 235, 235));
        jLabel28.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel28.setText("Referencia de entrega:");
        Nota.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 160, 20));

        jBGuardar.setBackground(new java.awt.Color(243, 240, 235));
        jBGuardar.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jBGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/s1.png"))); // NOI18N
        jBGuardar.setBorder(null);
        jBGuardar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/s2.png"))); // NOI18N
        jBGuardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/s2.png"))); // NOI18N
        jBGuardar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/s2.png"))); // NOI18N
        jBGuardar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/s2.png"))); // NOI18N
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });
        Nota.add(jBGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 390, 60, 60));
        Nota.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 150, -1));
        Nota.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 450, 150, -1));

        jScrollPane1.setViewportView(Nota);

        Nav.addTab("Nota", jScrollPane1);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Productos.setBackground(new java.awt.Color(243, 240, 235));
        Productos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLabel9.setText("Categoria:");
        Productos.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 110, -1));

        jLabel10.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Modelo:");
        Productos.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 20));

        jLabel12.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLabel12.setText("Precio:");
        Productos.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 100, 20));

        jLabel13.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLabel13.setText("Nombre:");
        Productos.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 90, 20));

        jLabel14.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLabel14.setText("Marca/Proveedor;");
        Productos.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 150, 20));

        jLabel15.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLabel15.setText("Cantidad:");
        Productos.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, 20));

        ap1.setBackground(new java.awt.Color(243, 240, 235));
        ap1.setBorder(null);
        ap1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ap1ActionPerformed(evt);
            }
        });
        Productos.add(ap1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 250, 20));

        nmo1.setBackground(new java.awt.Color(243, 240, 235));
        nmo1.setBorder(null);
        Productos.add(nmo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 250, 20));

        am1.setBackground(new java.awt.Color(243, 240, 235));
        am1.setBorder(null);
        am1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                am1ActionPerformed(evt);
            }
        });
        am1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                am1KeyTyped(evt);
            }
        });
        Productos.add(am1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 250, 20));

        name1.setBackground(new java.awt.Color(243, 240, 235));
        name1.setBorder(null);
        name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name1ActionPerformed(evt);
            }
        });
        Productos.add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 250, 20));

        email1.setBackground(new java.awt.Color(243, 240, 235));
        email1.setBorder(null);
        email1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email1ActionPerformed(evt);
            }
        });
        Productos.add(email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 250, 20));

        nmm1.setBackground(new java.awt.Color(243, 240, 235));
        nmm1.setBorder(null);
        nmm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmm1ActionPerformed(evt);
            }
        });
        Productos.add(nmm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 250, 20));

        jSeparator10.setBackground(new java.awt.Color(235, 235, 235));
        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));
        Productos.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 250, 10));

        jSeparator11.setBackground(new java.awt.Color(235, 235, 235));
        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        Productos.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 250, 10));

        jSeparator12.setBackground(new java.awt.Color(235, 235, 235));
        jSeparator12.setForeground(new java.awt.Color(0, 0, 0));
        Productos.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 250, 10));

        jSeparator13.setBackground(new java.awt.Color(235, 235, 235));
        jSeparator13.setForeground(new java.awt.Color(0, 0, 0));
        Productos.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 250, 10));

        jSeparator14.setBackground(new java.awt.Color(235, 235, 235));
        jSeparator14.setForeground(new java.awt.Color(0, 0, 0));
        Productos.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 250, 20));

        jSeparator15.setBackground(new java.awt.Color(235, 235, 235));
        jSeparator15.setForeground(new java.awt.Color(0, 0, 0));
        Productos.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 250, 10));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-search-48_1.png"))); // NOI18N
        Productos.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 50, 40));

        buscar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscar1KeyReleased(evt);
            }
        });
        Productos.add(buscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, 170, -1));

        jBGuardar1.setBackground(new java.awt.Color(243, 240, 235));
        jBGuardar1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jBGuardar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/s1.png"))); // NOI18N
        jBGuardar1.setText("Guardar");
        jBGuardar1.setBorder(null);
        jBGuardar1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/s2.png"))); // NOI18N
        jBGuardar1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/s2.png"))); // NOI18N
        jBGuardar1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/s2.png"))); // NOI18N
        jBGuardar1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/s2.png"))); // NOI18N
        jBGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardar1ActionPerformed(evt);
            }
        });
        Productos.add(jBGuardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 150, 60));

        agenda1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Modelo", "Nombre", "Precio", "Marca/Proveedor", "Catidad", "Categoria", "Imagen"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        agenda1.setRowHeight(70);
        agenda1.setSelectionBackground(new java.awt.Color(206, 166, 8));
        agenda1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agenda1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(agenda1);

        jScrollPane8.setViewportView(jScrollPane3);

        Productos.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 720, 350));

        jButton1.setText("Selecciona la imagen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Productos.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));
        Productos.add(txtFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 130, -1));

        jPanel4.add(Productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 520));

        Nav.addTab("Productos", jPanel4);

        Clientes.setBackground(new java.awt.Color(243, 240, 235));
        Clientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Clean.setText("Abonado");
        Clean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CleanActionPerformed(evt);
            }
        });
        Clientes.add(Clean, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 100, 30));

        buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarKeyReleased(evt);
            }
        });
        Clientes.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, 170, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-search-48_1.png"))); // NOI18N
        Clientes.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 50, 40));

        jTFuser3.setBackground(new java.awt.Color(243, 240, 235));
        jTFuser3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTFuser3.setForeground(new java.awt.Color(102, 102, 102));
        jTFuser3.setText("Inserte Cantidad");
        jTFuser3.setBorder(null);
        jTFuser3.setCaretColor(new java.awt.Color(204, 51, 0));
        jTFuser3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTFuser3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFuser3MouseClicked(evt);
            }
        });
        Clientes.add(jTFuser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, 110, 20));

        jSeparator16.setBackground(new java.awt.Color(235, 235, 235));
        jSeparator16.setForeground(new java.awt.Color(0, 0, 0));
        Clientes.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, 130, 10));

        jLabel11.setBackground(new java.awt.Color(235, 235, 235));
        jLabel11.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel11.setText("Cantidad:");
        Clientes.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 70, 20));

        agenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No. Nota", "Nombre", "Dirección", "Fecha de Compra", "Total a Pagar", "Abonado", "Saldo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        agenda.setColumnSelectionAllowed(true);
        agenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agendaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(agenda);
        agenda.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jScrollPane9.setViewportView(jScrollPane2);

        Clientes.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1050, 370));

        Nav.addTab("Clientes", Clientes);

        Entregas.setBackground(new java.awt.Color(243, 240, 235));
        Entregas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-search-48_1.png"))); // NOI18N
        Entregas.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 50, 40));

        buscar2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscar2KeyReleased(evt);
            }
        });
        Entregas.add(buscar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, 170, -1));

        agenda3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No. de Nota", "Nombre", "Dirección", "Referencia", "Fecha de Entrega", "Hora de Entrega", "Telefono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        agenda3.setColumnSelectionAllowed(true);
        agenda3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agenda3MouseClicked(evt);
            }
        });
        jScrollPane11.setViewportView(agenda3);
        agenda3.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jScrollPane10.setViewportView(jScrollPane11);

        Entregas.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1040, 370));

        Minimize1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        Minimize1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/pdf-40.png"))); // NOI18N
        Minimize1.setText("Exportar PDF");
        Minimize1.setBorder(null);
        Minimize1.setBorderPainted(false);
        Minimize1.setContentAreaFilled(false);
        Minimize1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Minimize1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/export-pdf-40.png"))); // NOI18N
        Minimize1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/export-pdf-40.png"))); // NOI18N
        Minimize1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/export-pdf-40.png"))); // NOI18N
        Minimize1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Minimize1ActionPerformed(evt);
            }
        });
        Entregas.add(Minimize1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 150, 40));

        Nav.addTab("Entregas", Entregas);

        Proveedores.setBackground(new java.awt.Color(243, 240, 235));
        Proveedores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nomprov.setBackground(new java.awt.Color(243, 240, 235));
        Nomprov.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Nomprov.setForeground(new java.awt.Color(102, 102, 102));
        Nomprov.setText("Inserta Nombre");
        Nomprov.setBorder(null);
        Nomprov.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NomprovMouseClicked(evt);
            }
        });
        Nomprov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomprovActionPerformed(evt);
            }
        });
        Nomprov.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NomprovKeyReleased(evt);
            }
        });
        Proveedores.add(Nomprov, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 44, 170, 20));

        jSeparator8.setBackground(new java.awt.Color(235, 235, 235));
        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        Proveedores.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 180, 10));

        jLabel2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel2.setText("Nombre del Provedor:");
        Proveedores.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 160, 30));

        buscar3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscar3KeyReleased(evt);
            }
        });
        Proveedores.add(buscar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, 170, -1));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-search-48_1.png"))); // NOI18N
        Proveedores.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 50, 40));

        dirccprove.setBackground(new java.awt.Color(243, 240, 235));
        dirccprove.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dirccprove.setForeground(new java.awt.Color(102, 102, 102));
        dirccprove.setText("Inserta Dirección");
        dirccprove.setBorder(null);
        dirccprove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dirccproveMouseClicked(evt);
            }
        });
        dirccprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dirccproveActionPerformed(evt);
            }
        });
        dirccprove.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dirccproveKeyReleased(evt);
            }
        });
        Proveedores.add(dirccprove, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 240, 20));

        jLabel3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel3.setText("Direccón:");
        Proveedores.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 70, 30));

        jSeparator9.setBackground(new java.awt.Color(235, 235, 235));
        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        Proveedores.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 250, 10));

        emailprov.setBackground(new java.awt.Color(243, 240, 235));
        emailprov.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        emailprov.setForeground(new java.awt.Color(102, 102, 102));
        emailprov.setText("Inserta Correo Electronico");
        emailprov.setBorder(null);
        emailprov.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailprovMouseClicked(evt);
            }
        });
        emailprov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailprovActionPerformed(evt);
            }
        });
        emailprov.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailprovKeyReleased(evt);
            }
        });
        Proveedores.add(emailprov, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 190, 20));

        jSeparator17.setBackground(new java.awt.Color(235, 235, 235));
        jSeparator17.setForeground(new java.awt.Color(0, 0, 0));
        Proveedores.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 200, 10));

        jLabel4.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel4.setText("Correo Electronico:");
        Proveedores.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 130, 30));

        telprov.setBackground(new java.awt.Color(243, 240, 235));
        telprov.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        telprov.setForeground(new java.awt.Color(102, 102, 102));
        telprov.setText("Inserta Telefono");
        telprov.setBorder(null);
        telprov.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                telprovMouseClicked(evt);
            }
        });
        telprov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telprovActionPerformed(evt);
            }
        });
        telprov.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                telprovKeyReleased(evt);
            }
        });
        Proveedores.add(telprov, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 290, 20));

        jSeparator18.setBackground(new java.awt.Color(235, 235, 235));
        jSeparator18.setForeground(new java.awt.Color(0, 0, 0));
        Proveedores.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 300, 10));

        jLabel17.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel17.setText("Telefono:");
        Proveedores.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 120, 30));

        jLabel18.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel18.setText("Mercancia:");
        Proveedores.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 80, 30));

        jSeparator19.setBackground(new java.awt.Color(235, 235, 235));
        jSeparator19.setForeground(new java.awt.Color(0, 0, 0));
        Proveedores.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 250, 10));

        mercprov.setBackground(new java.awt.Color(243, 240, 235));
        mercprov.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mercprov.setForeground(new java.awt.Color(102, 102, 102));
        mercprov.setText("Inserta Mercancia");
        mercprov.setBorder(null);
        mercprov.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mercprovMouseClicked(evt);
            }
        });
        mercprov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mercprovActionPerformed(evt);
            }
        });
        mercprov.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mercprovKeyReleased(evt);
            }
        });
        Proveedores.add(mercprov, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 240, 20));

        agenda4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Dirección", "Apellido", "No. Telefonico", "Correo", "Tipo de Mercancia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        agenda4.setColumnSelectionAllowed(true);
        agenda4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agenda4MouseClicked(evt);
            }
        });
        jScrollPane12.setViewportView(agenda4);
        agenda4.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (agenda4.getColumnModel().getColumnCount() > 0) {
            agenda4.getColumnModel().getColumn(5).setHeaderValue("Tipo de Mercancia");
        }

        jScrollPane4.setViewportView(jScrollPane12);

        Proveedores.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 990, 290));

        Add1.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        Add1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/add2.png"))); // NOI18N
        Add1.setBorder(null);
        Add1.setBorderPainted(false);
        Add1.setContentAreaFilled(false);
        Add1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Add1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/add1.png"))); // NOI18N
        Add1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/add1.png"))); // NOI18N
        Add1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/add1.png"))); // NOI18N
        Add1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Add1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Add1MouseReleased(evt);
            }
        });
        Add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add1ActionPerformed(evt);
            }
        });
        Proveedores.add(Add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, 40));

        Nav.addTab("Proveedores", Proveedores);

        Bitacora.setBackground(new java.awt.Color(243, 240, 235));
        Bitacora.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        agenda5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Clave Administrador", "Acción", "Cantidad Recibida", "No. Nota", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        agenda5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agenda5MouseClicked(evt);
            }
        });
        jScrollPane13.setViewportView(agenda5);
        agenda5.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        Bitacora.add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 960, 430));

        Date1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        Date1.setText("Fecha: XXXXXX");
        Bitacora.add(Date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 150, 40));

        Minimize2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        Minimize2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/pdf-40.png"))); // NOI18N
        Minimize2.setText("Exportar PDF");
        Minimize2.setBorder(null);
        Minimize2.setBorderPainted(false);
        Minimize2.setContentAreaFilled(false);
        Minimize2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Minimize2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/export-pdf-40.png"))); // NOI18N
        Minimize2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/export-pdf-40.png"))); // NOI18N
        Minimize2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/export-pdf-40.png"))); // NOI18N
        Minimize2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Minimize2ActionPerformed(evt);
            }
        });
        Bitacora.add(Minimize2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 150, 40));

        Nav.addTab("Bitacora", Bitacora);

        jPanel1.add(Nav, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 550));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1050, 550));

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Microsoft Tai Le", 1, 28)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/engranajes.png"))); // NOI18N
        jLabel8.setText("Centro de trabajo");
        jPanel10.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 70));

        Shutdown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/Shutdown1.png"))); // NOI18N
        Shutdown.setBorder(null);
        Shutdown.setBorderPainted(false);
        Shutdown.setContentAreaFilled(false);
        Shutdown.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Shutdown.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/Shutdown2.png"))); // NOI18N
        Shutdown.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/Shutdown2.png"))); // NOI18N
        Shutdown.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/Shutdown2.png"))); // NOI18N
        Shutdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShutdownActionPerformed(evt);
            }
        });
        jPanel10.add(Shutdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, -1, 40));

        Minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/Minimize.png"))); // NOI18N
        Minimize.setBorder(null);
        Minimize.setBorderPainted(false);
        Minimize.setContentAreaFilled(false);
        Minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Minimize.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/Minimize2.png"))); // NOI18N
        Minimize.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/Minimize2.png"))); // NOI18N
        Minimize.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/Minimize2.png"))); // NOI18N
        Minimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimizeActionPerformed(evt);
            }
        });
        jPanel10.add(Minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, -1, 40));

        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/close.png"))); // NOI18N
        Close.setBorder(null);
        Close.setBorderPainted(false);
        Close.setContentAreaFilled(false);
        Close.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Close.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/close2.png"))); // NOI18N
        Close.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/close2.png"))); // NOI18N
        Close.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/close2.png"))); // NOI18N
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });
        jPanel10.add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, -1, 40));

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimizeActionPerformed
        this.setState(PC.ICONIFIED);
    }//GEN-LAST:event_MinimizeActionPerformed

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "Desea Salir?","Exit",dialog);
        if (result==0){
            System.exit(0);
        }
    }//GEN-LAST:event_CloseActionPerformed

    private void ShutdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShutdownActionPerformed
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "Cerrando Sesión\nEstas seguro de salir ?","Exit",dialog);
        if (result==0){
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
        }
        this.dispose();
    }//GEN-LAST:event_ShutdownActionPerformed

    private void NavMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NavMousePressed
        //        // TODO add your handling code here:
        //        buscar.setText("");
        //        buscar1.setText("");
        //        String filtro=buscar.getText();
        //        if(!filtro.equals("")){
            //            tr.setRowFilter(RowFilter.regexFilter(filtro));
            //        }else{
            //            tr.setRowFilter(null);
            //        }
        //        String filtro2=buscar1.getText();
        //        if(!filtro2.equals("")){
            //            tr2.setRowFilter(RowFilter.regexFilter(filtro));
            //        }else{
            //            tr2.setRowFilter(null);
            //        }
    }//GEN-LAST:event_NavMousePressed

    private void agenda1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agenda1MouseClicked
        //        // TODO add your handling code here:
        //        fslt=agenda1.getSelectedRow();
        //        name1.setText(agenda1.getValueAt(fslt, 0).toString());
        //        ap1.setText(agenda1.getValueAt(fslt, 1).toString());
        //        am1.setText(agenda1.getValueAt(fslt, 2).toString());
        //        nmm1.setText(agenda1.getValueAt(fslt, 3).toString());
        //        nmo1.setText(agenda1.getValueAt(fslt, 4).toString());
        //        email1.setText(agenda1.getValueAt(fslt, 5).toString());
        //        data3[0]=agenda1.getValueAt(fslt, 0).toString();
        //        data3[1]=agenda1.getValueAt(fslt, 1).toString();
        //        data3[2]=agenda1.getValueAt(fslt, 2).toString();
        //        data3[3]=agenda1.getValueAt(fslt, 3).toString();
        //        data3[4]=agenda1.getValueAt(fslt, 4).toString();
        //        data3[5]=agenda1.getValueAt(fslt, 5).toString();
        //        filas=fslt;
    }//GEN-LAST:event_agenda1MouseClicked

    private void buscar1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscar1KeyReleased
        //        // TODO add your handling code here:
        //        String filtro=buscar1.getText();
        //        if(!filtro.equals("")){
            //            tr2.setRowFilter(RowFilter.regexFilter(filtro));
            //        }else{
            //            tr2.setRowFilter(null);
            //        }
    }//GEN-LAST:event_buscar1KeyReleased

    private void name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name1ActionPerformed
        // TODO add your handling code here:
        ap1.requestFocus ();
        
    }//GEN-LAST:event_name1ActionPerformed

    private void ap1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ap1ActionPerformed
        // TODO add your handling code here:
        am1.requestFocus ();
    }//GEN-LAST:event_ap1ActionPerformed

    private void Minimize1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Minimize1ActionPerformed

    }//GEN-LAST:event_Minimize1ActionPerformed

    private void agenda3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agenda3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_agenda3MouseClicked

    private void buscar2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscar2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_buscar2KeyReleased

    private void agendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agendaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_agendaMouseClicked

    private void jTFuser3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFuser3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFuser3MouseClicked

    private void buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarKeyReleased
        //        // TODO add your handling code here:
        //        String filtro=buscar.getText();
        //        if(!filtro.equals("")){
            //            tr.setRowFilter(RowFilter.regexFilter(filtro));
            //        }else{
            //            tr.setRowFilter(null);
            //        }
    }//GEN-LAST:event_buscarKeyReleased

    private void CleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CleanActionPerformed
        // TODO add your handling code here:
        //        String cad;
        //        fslt=agenda.getSelectedRow();
        //        data[0]=agenda1.getValueAt(fslt, 0).toString();
        //        data[1]=agenda1.getValueAt(fslt, 1).toString();
        //        data[2]=agenda1.getValueAt(fslt, 2).toString();
        //        data[3]=agenda1.getValueAt(fslt, 3).toString();
        //        data[4]=agenda1.getValueAt(fslt, 4).toString();
        //        data[5]=agenda1.getValueAt(fslt, 5).toString();
        //        cad=data[0]+"--"+data[1]+"--"+data[2]+"--"+data[3]+"--"+data[4]+"--"+data[5];
        //        if (agenda.getSelectedRow()!=-1) {
            //            removeLineFromFile(cad);
            //            modelo.removeRow(agenda.getSelectedRow());
            //        }else{
            //            JOptionPane.showMessageDialog(null, "Debes seleccionar para poder Eliminar!");
            //        }
    }//GEN-LAST:event_CleanActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        //        java.awt.EventQueue.invokeLater(new Runnable() {
            //            public void run() {
                //                new exa().setVisible(true);
                //            }
            //        });
    //        this.dispose();
    InfoClientes ir= new InfoClientes();
    ir.setVisible(true);
    ir.setLocationRelativeTo(null);
    this.dispose();
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "Se guardado con exito :3","Exit",dialog);
        if (result==0){

        }
    }//GEN-LAST:event_AddActionPerformed

    private void AddMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_AddMouseReleased

    private void AddMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMousePressed

    }//GEN-LAST:event_AddMousePressed

    private void jTFuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFuserMouseClicked
        // TODO add your handling code here:
        if (jTFuser.getText().equals("Ingrese Usuario")) {
            jTFuser.setText("");
        }
    }//GEN-LAST:event_jTFuserMouseClicked

    private void jTFuser1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFuser1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFuser1MouseClicked

    private void jTFuser2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFuser2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFuser2ActionPerformed

    private void jTFuser2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFuser2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFuser2MouseClicked

    private void Add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add1ActionPerformed
        // TODO add your handling code here:
        q = new Querys();
         llenarclaseprovedores();
             String valores1 =("'"+prov.getNombre() + "',");
                                    valores1 +=("'"+prov.getDireccion()+ "',");
                                    valores1 += ("'"+prov.getCorreo() + "',");
                                    valores1 += ("'"+prov.getTelefono() + "',");
                                    valores1 += ("'"+prov.getTipoMer()+"'");
                                   
                                    
            
        String s1 = q.Insertar(con, "provedores"," nombre_empresa, direccion, correo, telefono, mercancia ", valores1);
        if (s1 != null)
        {    Mensaje.error(this, s1);
            System.out.println("valio queso");
        } else
        {
             System.out.println("Exito");
        }
        
    }//GEN-LAST:event_Add1ActionPerformed

    private void Add1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_Add1MouseReleased

    private void Add1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Add1MousePressed

    private void agenda4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agenda4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_agenda4MouseClicked

    private void mercprovKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mercprovKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_mercprovKeyReleased

    private void mercprovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mercprovActionPerformed
        // TODO add your handling code here:
        ((JTextField) evt.getSource()).transferFocus();
    }//GEN-LAST:event_mercprovActionPerformed

    private void mercprovMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mercprovMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mercprovMouseClicked

    private void telprovKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telprovKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_telprovKeyReleased

    private void telprovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telprovActionPerformed
        // TODO add your handling code here:
        ((JTextField) evt.getSource()).transferFocus();
    }//GEN-LAST:event_telprovActionPerformed

    private void telprovMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_telprovMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_telprovMouseClicked

    private void emailprovKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailprovKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_emailprovKeyReleased

    private void emailprovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailprovActionPerformed
        // TODO add your handling code here:
        ((JTextField) evt.getSource()).transferFocus();
    }//GEN-LAST:event_emailprovActionPerformed

    private void emailprovMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailprovMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_emailprovMouseClicked

    private void dirccproveKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dirccproveKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_dirccproveKeyReleased

    private void dirccproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dirccproveActionPerformed
        // TODO add your handling code here:
        ((JTextField) evt.getSource()).transferFocus();
    }//GEN-LAST:event_dirccproveActionPerformed

    private void dirccproveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dirccproveMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dirccproveMouseClicked

    private void buscar3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscar3KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_buscar3KeyReleased

    private void NomprovKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NomprovKeyReleased
        if (Nomprov.getText().equals("Inserta un correo electronico")) {
            Nomprov.setText("");
        }
    }//GEN-LAST:event_NomprovKeyReleased

    private void NomprovMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NomprovMouseClicked
        // TODO add your handling code here:
        if (Nomprov.getText().equals("Inserta un correo electronico")) {
            Nomprov.setText("");
        }
    }//GEN-LAST:event_NomprovMouseClicked

    private void agenda5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agenda5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_agenda5MouseClicked

    private void Minimize2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Minimize2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Minimize2ActionPerformed

    private void jBGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardar1ActionPerformed
        // TODO add your handling code here:
        try{
            q = new Querys();
         llenarclaseproductos();
             String valores1 =("'"+cli.getModeloPro() + "',");
                                    valores1 +=("'"+cli.getNombrePro()+ "',");
                                    valores1 += (cli.getPrecio() + ",");
                                    valores1 += (cli.getExistencia() + ",");
                                    valores1 += ("'"+cli.getCategoria()+"',");
                                    valores1 += ("'"+cli.getProvedMarca()+ "'");
                                    
        agregarProductos(cli.getModeloPro(),cli.getNombrePro(),cli.getPrecio(),cli.getExistencia(),cli.getCategoria(),cli.getProvedMarca(),jf.getSelectedFile().getAbsolutePath().replace("\\","/"));     
        String s1 = q.Insertar(con, "productos"," idmodelo, nombre, precio, existencia, clasificacion, provedores_id ", valores1);
        if (s1 != null)
        {    Mensaje.error(this, s1);
            System.out.println("valio queso");
        } else
        {
             System.out.println("Exito");
        }
       
        
        }catch(Exception e){
            if(txtFile.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Falta Seleccionar una imagen ","Selecciona Imagen",JOptionPane.INFORMATION_MESSAGE);
            }
        }
          
         
    }//GEN-LAST:event_jBGuardar1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         con = ManipulaDBC.conectaDB();
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        ManipulaDBC.desconectaDB(con);
    }//GEN-LAST:event_formWindowClosed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         jf = new JFileChooser();
        FileNameExtensionFilter fil = new FileNameExtensionFilter("JPG, PNG & GIF","jpg","png","gif");
        jf.setFileFilter(fil);
        jf.setCurrentDirectory(new File("D:\\ejercicios\\OceansCoffe System IotEarth\\src\\IMG2"));
        int el = jf.showOpenDialog(this);
        if(el == JFileChooser.APPROVE_OPTION){
            //txtRuta.setText(jf.getSelectedFile().getAbsolutePath());
            txtFile.setText(jf.getSelectedFile().getName());
           
            //lblFoto.setIcon(new ImageIcon(txtRuta.getText()));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void am1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_am1KeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isLetter(c) ) {
		getToolkit().beep();
 
		evt.consume();
 
	}  
    }//GEN-LAST:event_am1KeyTyped

    private void NomprovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomprovActionPerformed
        // TODO add your handling code here:
        ((JTextField) evt.getSource()).transferFocus();
    }//GEN-LAST:event_NomprovActionPerformed

    private void am1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_am1ActionPerformed
        // TODO add your handling code here:
        email1.requestFocus ();
    }//GEN-LAST:event_am1ActionPerformed

    private void email1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email1ActionPerformed
        // TODO add your handling code here:
        nmm1.requestFocus ();
    }//GEN-LAST:event_email1ActionPerformed

    private void nmm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmm1ActionPerformed
        // TODO add your handling code here:
        nmo1.requestFocus ();
    }//GEN-LAST:event_nmm1ActionPerformed
    public void llenarclaseproductos(){
        cli= new clientes();
        cli.setModeloPro(name1.getText());
        cli.setNombrePro(ap1.getText());
        cli.setPrecio(Double.parseDouble(am1.getText()));
        cli.setProvedMarca(email1.getText());
        cli.setExistencia(Integer.parseInt(nmm1.getText()));
        cli.setCategoria(nmo1.getText());
    }
    public void llenarclaseprovedores(){
        prov=new Provedores();
        prov.setNombre(Nomprov.getText());
        prov.setCorreo(emailprov.getText());
        prov.setTipoMer(mercprov.getText());
        prov.setDireccion(dirccprove.getText());
        prov.setTelefono(telprov.getText());
    }
     public void agregarProductos(String mod,String nom,Double preci, int exis,String cate,String provM,String im){
      atm.addRow(new Object[]{
          mod,nom,preci,exis,cate,provM,new JLabel(reducirtamamo(im))
      });
   }
   public ImageIcon reducirtamamo(String im){
      ImageIcon img= new ImageIcon(im);
      Image conver=img.getImage();
      Image tam=conver.getScaledInstance(100,120,Image.SCALE_SMOOTH);
      ImageIcon imgfinal=new ImageIcon(tam);
      
      return imgfinal;
   }
   
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PC().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Add1;
    private javax.swing.JPanel Bitacora;
    private javax.swing.JButton Clean;
    private javax.swing.JPanel Clientes;
    private javax.swing.JButton Close;
    private javax.swing.JLabel Date;
    private javax.swing.JLabel Date1;
    private javax.swing.JPanel Entregas;
    private javax.swing.JButton Minimize;
    private javax.swing.JButton Minimize1;
    private javax.swing.JButton Minimize2;
    private javax.swing.JLabel NNote;
    public javax.swing.JTabbedPane Nav;
    private javax.swing.JTextField Nomprov;
    private javax.swing.JPanel Nota;
    private javax.swing.JPanel Productos;
    private javax.swing.JPanel Proveedores;
    private javax.swing.JButton Shutdown;
    private javax.swing.JLabel Total;
    private javax.swing.JTable agenda;
    private javax.swing.JTable agenda1;
    private javax.swing.JTable agenda3;
    private javax.swing.JTable agenda4;
    private javax.swing.JTable agenda5;
    private javax.swing.JTextField am1;
    private javax.swing.JTextField ap1;
    private javax.swing.JTextField buscar;
    private javax.swing.JTextField buscar1;
    private javax.swing.JTextField buscar2;
    private javax.swing.JTextField buscar3;
    private javax.swing.JTextField dirccprove;
    private javax.swing.JTextField email1;
    private javax.swing.JTextField emailprov;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBGuardar1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.toedter.components.JLocaleChooser jLocaleChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTFuser;
    private javax.swing.JTextField jTFuser1;
    private javax.swing.JTextField jTFuser2;
    private javax.swing.JTextField jTFuser3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField mercprov;
    private javax.swing.JTextField name1;
    private javax.swing.JTextField nmm1;
    private javax.swing.JTextField nmo1;
    private javax.swing.JTextField telprov;
    private javax.swing.JTextField txtFile;
    // End of variables declaration//GEN-END:variables
}
