/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LogIn;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Rasteck7
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Registro");
        ImageIcon icon = new ImageIcon("src/Imagen/LogoMonza.png");
        this.setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Question = new javax.swing.JComboBox<>();
        jBGuardar = new javax.swing.JButton();
        jBLimpiar = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTFuser = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jTFAmaterno = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jTFNombreUser = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        Ocultar = new javax.swing.JToggleButton();
        jLabel10 = new javax.swing.JLabel();
        jTFRespuesta = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jTFApaterno = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jTFCorreo = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        Minimize = new javax.swing.JButton();
        Close = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTFCorreo1 = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jPassword2 = new javax.swing.JPasswordField();
        Ocultar2 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(243, 240, 235));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Question.setBackground(new java.awt.Color(33, 33, 33));
        Question.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 11)); // NOI18N
        Question.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "¿Cuál fue el nombre de tu primera mascota? ", "¿Cuál es tu comida favorita? ", "¿Cuál es el nombre de tu madre? ", "¿En qué ciudad naciste?", "¿Cuál es el segundo nombre de tu padre?", "¿Cuál es el nombre de tu primer profesor?" }));
        Question.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuestionActionPerformed(evt);
            }
        });
        jPanel1.add(Question, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, 290, 30));

        jBGuardar.setBackground(new java.awt.Color(243, 240, 235));
        jBGuardar.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jBGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/s1.png"))); // NOI18N
        jBGuardar.setText("Guardar");
        jBGuardar.setBorder(null);
        jBGuardar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/s2.png"))); // NOI18N
        jBGuardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/s2.png"))); // NOI18N
        jBGuardar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/s2.png"))); // NOI18N
        jBGuardar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/s2.png"))); // NOI18N
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jBGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 150, 60));

        jBLimpiar.setBackground(new java.awt.Color(243, 240, 235));
        jBLimpiar.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jBLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/eraser1.png"))); // NOI18N
        jBLimpiar.setText("Limpiar");
        jBLimpiar.setBorder(null);
        jBLimpiar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/eraser2.png"))); // NOI18N
        jBLimpiar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/eraser2.png"))); // NOI18N
        jBLimpiar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/eraser2.png"))); // NOI18N
        jBLimpiar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/eraser2.png"))); // NOI18N
        jBLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(jBLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, 140, 60));

        back.setBackground(new java.awt.Color(243, 240, 235));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/Skip1.png"))); // NOI18N
        back.setBorder(null);
        back.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/Skip2.png"))); // NOI18N
        back.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/Skip2.png"))); // NOI18N
        back.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/Skip2.png"))); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 510, 80, 60));

        jLabel5.setBackground(new java.awt.Color(235, 235, 235));
        jLabel5.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel5.setText("Usuario");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 60, 20));

        jTFuser.setBackground(new java.awt.Color(243, 240, 235));
        jTFuser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTFuser.setForeground(new java.awt.Color(102, 102, 102));
        jTFuser.setText("Ingrese Usuario");
        jTFuser.setBorder(null);
        jTFuser.setCaretColor(new java.awt.Color(204, 51, 0));
        jTFuser.setCaretPosition(0);
        jTFuser.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTFuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFuserMouseClicked(evt);
            }
        });
        jPanel1.add(jTFuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 230, 30));

        jSeparator3.setBackground(new java.awt.Color(235, 235, 235));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 250, 20));

        jSeparator7.setBackground(new java.awt.Color(235, 235, 235));
        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 250, 20));

        jLabel6.setBackground(new java.awt.Color(235, 235, 235));
        jLabel6.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel6.setText("Contraseña");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 90, 20));

        jLabel7.setBackground(new java.awt.Color(235, 235, 235));
        jLabel7.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel7.setText("Apellido Materno");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 130, 20));

        jSeparator9.setBackground(new java.awt.Color(235, 235, 235));
        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 250, 10));

        jTFAmaterno.setBackground(new java.awt.Color(243, 240, 235));
        jTFAmaterno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTFAmaterno.setForeground(new java.awt.Color(102, 102, 102));
        jTFAmaterno.setText("Ingrese A. Materno");
        jTFAmaterno.setBorder(null);
        jTFAmaterno.setCaretColor(new java.awt.Color(204, 51, 0));
        jTFAmaterno.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTFAmaterno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFAmaternoMouseClicked(evt);
            }
        });
        jPanel1.add(jTFAmaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 230, 40));

        jSeparator11.setBackground(new java.awt.Color(235, 235, 235));
        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 250, 20));

        jTFNombreUser.setBackground(new java.awt.Color(243, 240, 235));
        jTFNombreUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTFNombreUser.setForeground(new java.awt.Color(102, 102, 102));
        jTFNombreUser.setText("Inserte nombre");
        jTFNombreUser.setBorder(null);
        jTFNombreUser.setCaretColor(new java.awt.Color(204, 51, 0));
        jTFNombreUser.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTFNombreUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFNombreUserMouseClicked(evt);
            }
        });
        jPanel1.add(jTFNombreUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 230, 30));

        jLabel9.setBackground(new java.awt.Color(235, 235, 235));
        jLabel9.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel9.setText("Pregunta de seguridad");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, 160, 20));

        jPassword.setBackground(new java.awt.Color(243, 240, 235));
        jPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPassword.setForeground(new java.awt.Color(102, 102, 102));
        jPassword.setText("Inserte contraseña");
        jPassword.setBorder(null);
        jPassword.setCaretColor(new java.awt.Color(204, 51, 0));
        jPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordMouseClicked(evt);
            }
        });
        jPanel1.add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, 220, 30));

        Ocultar.setBackground(new java.awt.Color(242, 242, 242));
        Ocultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/oculto.png"))); // NOI18N
        Ocultar.setBorder(null);
        Ocultar.setBorderPainted(false);
        Ocultar.setContentAreaFilled(false);
        Ocultar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/ver.png"))); // NOI18N
        Ocultar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/ver.png"))); // NOI18N
        Ocultar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/ver.png"))); // NOI18N
        Ocultar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/ver.png"))); // NOI18N
        Ocultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OcultarActionPerformed(evt);
            }
        });
        jPanel1.add(Ocultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 160, 20, 20));

        jLabel10.setBackground(new java.awt.Color(235, 235, 235));
        jLabel10.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel10.setText("Nombre(s)");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 90, 20));

        jTFRespuesta.setBackground(new java.awt.Color(243, 240, 235));
        jTFRespuesta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTFRespuesta.setForeground(new java.awt.Color(102, 102, 102));
        jTFRespuesta.setText("Inserte respuesta");
        jTFRespuesta.setBorder(null);
        jTFRespuesta.setCaretColor(new java.awt.Color(204, 51, 0));
        jTFRespuesta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTFRespuesta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFRespuestaMouseClicked(evt);
            }
        });
        jTFRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFRespuestaActionPerformed(evt);
            }
        });
        jPanel1.add(jTFRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 480, 250, 30));

        jSeparator12.setBackground(new java.awt.Color(235, 235, 235));
        jSeparator12.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 520, 250, 20));

        jLabel11.setBackground(new java.awt.Color(235, 235, 235));
        jLabel11.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel11.setText("Apellido Paterno");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 130, 20));

        jTFApaterno.setBackground(new java.awt.Color(243, 240, 235));
        jTFApaterno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTFApaterno.setForeground(new java.awt.Color(102, 102, 102));
        jTFApaterno.setText("Ingrese A. Paterno");
        jTFApaterno.setBorder(null);
        jTFApaterno.setCaretColor(new java.awt.Color(204, 51, 0));
        jTFApaterno.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTFApaterno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFApaternoMouseClicked(evt);
            }
        });
        jPanel1.add(jTFApaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 230, 30));

        jSeparator10.setBackground(new java.awt.Color(235, 235, 235));
        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 250, 20));

        jLabel13.setBackground(new java.awt.Color(235, 235, 235));
        jLabel13.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel13.setText("Correo electronico");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 130, 20));

        jTFCorreo.setBackground(new java.awt.Color(243, 240, 235));
        jTFCorreo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTFCorreo.setForeground(new java.awt.Color(102, 102, 102));
        jTFCorreo.setText("Inserte un correo electronico");
        jTFCorreo.setBorder(null);
        jTFCorreo.setCaretColor(new java.awt.Color(204, 51, 0));
        jTFCorreo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTFCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFCorreoMouseClicked(evt);
            }
        });
        jTFCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCorreoActionPerformed(evt);
            }
        });
        jPanel1.add(jTFCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, 230, 30));

        jSeparator13.setBackground(new java.awt.Color(235, 235, 235));
        jSeparator13.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, 250, 20));

        jLabel8.setFont(new java.awt.Font("Microsoft Tai Le", 0, 36)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/Register.png"))); // NOI18N
        jLabel8.setText("Registro");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 380, 70));

        Minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/Minimize.png"))); // NOI18N
        Minimize.setBorder(null);
        Minimize.setBorderPainted(false);
        Minimize.setContentAreaFilled(false);
        Minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Minimize.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/Minimize2.png"))); // NOI18N
        Minimize.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/Minimize2.png"))); // NOI18N
        Minimize.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/Minimize2.png"))); // NOI18N
        Minimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimizeActionPerformed(evt);
            }
        });
        jPanel1.add(Minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, -1, 40));

        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/close.png"))); // NOI18N
        Close.setBorder(null);
        Close.setBorderPainted(false);
        Close.setContentAreaFilled(false);
        Close.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Close.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/close2.png"))); // NOI18N
        Close.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/close2.png"))); // NOI18N
        Close.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/close2.png"))); // NOI18N
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });
        jPanel1.add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, -1, 40));

        jLabel14.setBackground(new java.awt.Color(235, 235, 235));
        jLabel14.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel14.setText("Correo electronico");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 130, 20));

        jTFCorreo1.setBackground(new java.awt.Color(243, 240, 235));
        jTFCorreo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTFCorreo1.setForeground(new java.awt.Color(102, 102, 102));
        jTFCorreo1.setText("Inserte un correo electronico");
        jTFCorreo1.setBorder(null);
        jTFCorreo1.setCaretColor(new java.awt.Color(204, 51, 0));
        jTFCorreo1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTFCorreo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFCorreo1MouseClicked(evt);
            }
        });
        jTFCorreo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCorreo1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTFCorreo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, 230, 30));

        jSeparator14.setBackground(new java.awt.Color(235, 235, 235));
        jSeparator14.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, 250, 20));

        jSeparator8.setBackground(new java.awt.Color(235, 235, 235));
        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 250, 20));

        jLabel12.setBackground(new java.awt.Color(235, 235, 235));
        jLabel12.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel12.setText("Confirmar Contraseña");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 170, 20));

        jPassword2.setBackground(new java.awt.Color(243, 240, 235));
        jPassword2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPassword2.setForeground(new java.awt.Color(102, 102, 102));
        jPassword2.setText("Inserte contraseña");
        jPassword2.setBorder(null);
        jPassword2.setCaretColor(new java.awt.Color(204, 51, 0));
        jPassword2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPassword2MouseClicked(evt);
            }
        });
        jPanel1.add(jPassword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 220, 30));

        Ocultar2.setBackground(new java.awt.Color(242, 242, 242));
        Ocultar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/oculto.png"))); // NOI18N
        Ocultar2.setBorder(null);
        Ocultar2.setBorderPainted(false);
        Ocultar2.setContentAreaFilled(false);
        Ocultar2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/ver.png"))); // NOI18N
        Ocultar2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/ver.png"))); // NOI18N
        Ocultar2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/ver.png"))); // NOI18N
        Ocultar2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/ver.png"))); // NOI18N
        Ocultar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ocultar2ActionPerformed(evt);
            }
        });
        jPanel1.add(Ocultar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 270, 20, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void QuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuestionActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new exa().setVisible(true);
//            }
//        });
//        this.dispose();
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBLimpiarActionPerformed

    private void jTFuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFuserMouseClicked
        // TODO add your handling code here:
        if (jTFuser.getText().equals("Ingrese Usuario")) {
            jTFuser.setText("");
        }
    }//GEN-LAST:event_jTFuserMouseClicked

    private void jTFAmaternoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFAmaternoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFAmaternoMouseClicked

    private void jTFNombreUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFNombreUserMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNombreUserMouseClicked

    private void jPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordMouseClicked
        // TODO add your handling code here:
        if (jPassword.getText().equals("Inserte contraseña")) {
            jPassword.setText("");
        }
    }//GEN-LAST:event_jPasswordMouseClicked

    private void OcultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OcultarActionPerformed
        if (Ocultar.isSelected()==true) {
            jPassword.setEchoChar((char)0);
        }else{
            jPassword.setEchoChar('•');

        }
    }//GEN-LAST:event_OcultarActionPerformed

    private void jTFRespuestaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFRespuestaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFRespuestaMouseClicked

    private void jTFRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFRespuestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFRespuestaActionPerformed

    private void jTFApaternoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFApaternoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFApaternoMouseClicked

    private void jTFCorreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFCorreoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCorreoMouseClicked

    private void jTFCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCorreoActionPerformed

    private void MinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimizeActionPerformed
        this.setState(LogIn.ICONIFIED);
    }//GEN-LAST:event_MinimizeActionPerformed

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "Desea regresar al inicio?","Exit",dialog);
        if (result==0){
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
        }
        this.dispose();
    }//GEN-LAST:event_CloseActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true); //abrir el FrameHome que es nuestro Menu
            }
        });
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void jTFCorreo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFCorreo1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCorreo1MouseClicked

    private void jTFCorreo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCorreo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCorreo1ActionPerformed

    private void jPassword2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPassword2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPassword2MouseClicked

    private void Ocultar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ocultar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ocultar2ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Registro().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Close;
    private javax.swing.JButton Minimize;
    private javax.swing.JToggleButton Ocultar;
    private javax.swing.JToggleButton Ocultar2;
    private javax.swing.JComboBox<String> Question;
    private javax.swing.JButton back;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBLimpiar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JPasswordField jPassword2;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTFAmaterno;
    private javax.swing.JTextField jTFApaterno;
    private javax.swing.JTextField jTFCorreo;
    private javax.swing.JTextField jTFCorreo1;
    private javax.swing.JTextField jTFNombreUser;
    private javax.swing.JTextField jTFRespuesta;
    private javax.swing.JTextField jTFuser;
    // End of variables declaration//GEN-END:variables
}
