/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LogIn;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Rasteck7
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Registro");
        ImageIcon icon = new ImageIcon("src/Imagen/LogoMonza.png");
        this.setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        horario = new javax.swing.JComboBox<>();
        jBGuardar = new javax.swing.JButton();
        jBLimpiar = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTFuser = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jTFuser2 = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jTFuser3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        Ocultar = new javax.swing.JToggleButton();
        jLabel10 = new javax.swing.JLabel();
        jTFuser1 = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jTFuser4 = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jTFuser5 = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        Minimize = new javax.swing.JButton();
        Close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(243, 240, 235));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        horario.setBackground(new java.awt.Color(33, 33, 33));
        horario.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 11)); // NOI18N
        horario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8:00AM -  3:30PM", "8:00AM -  6:00PM", "8:00AM -  8:00PM", "3:30AM -  8:30PM" }));
        horario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horarioActionPerformed(evt);
            }
        });
        jPanel1.add(horario, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, 230, 30));

        jBGuardar.setBackground(new java.awt.Color(243, 240, 235));
        jBGuardar.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jBGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/s1.png"))); // NOI18N
        jBGuardar.setText("Guardar");
        jBGuardar.setBorder(null);
        jBGuardar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/s2.png"))); // NOI18N
        jBGuardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/s2.png"))); // NOI18N
        jBGuardar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/s2.png"))); // NOI18N
        jBGuardar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/s2.png"))); // NOI18N
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jBGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 150, 60));

        jBLimpiar.setBackground(new java.awt.Color(243, 240, 235));
        jBLimpiar.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jBLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/eraser1.png"))); // NOI18N
        jBLimpiar.setText("Limpiar");
        jBLimpiar.setBorder(null);
        jBLimpiar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/eraser2.png"))); // NOI18N
        jBLimpiar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/eraser2.png"))); // NOI18N
        jBLimpiar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/eraser2.png"))); // NOI18N
        jBLimpiar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/eraser2.png"))); // NOI18N
        jBLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(jBLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, 140, 60));

        back.setBackground(new java.awt.Color(243, 240, 235));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/Skip1.png"))); // NOI18N
        back.setBorder(null);
        back.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/Skip2.png"))); // NOI18N
        back.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/Skip2.png"))); // NOI18N
        back.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/Skip2.png"))); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 490, 80, 60));

        jLabel5.setBackground(new java.awt.Color(235, 235, 235));
        jLabel5.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel5.setText("Usuario");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 60, 20));

        jTFuser.setBackground(new java.awt.Color(243, 240, 235));
        jTFuser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTFuser.setForeground(new java.awt.Color(102, 102, 102));
        jTFuser.setText("Ingrese Usuario");
        jTFuser.setBorder(null);
        jTFuser.setCaretColor(new java.awt.Color(204, 51, 0));
        jTFuser.setCaretPosition(0);
        jTFuser.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTFuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFuserMouseClicked(evt);
            }
        });
        jPanel1.add(jTFuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 230, 40));

        jSeparator3.setBackground(new java.awt.Color(235, 235, 235));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 250, 20));

        jSeparator7.setBackground(new java.awt.Color(235, 235, 235));
        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 250, 20));

        jLabel6.setBackground(new java.awt.Color(235, 235, 235));
        jLabel6.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel6.setText("Contraseña");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 90, 20));

        jLabel7.setBackground(new java.awt.Color(235, 235, 235));
        jLabel7.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel7.setText("Apellido Paterno");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, 130, 20));

        jSeparator9.setBackground(new java.awt.Color(235, 235, 235));
        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 250, 20));

        jTFuser2.setBackground(new java.awt.Color(243, 240, 235));
        jTFuser2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTFuser2.setForeground(new java.awt.Color(102, 102, 102));
        jTFuser2.setText("Ingrese A. Paterno");
        jTFuser2.setBorder(null);
        jTFuser2.setCaretColor(new java.awt.Color(204, 51, 0));
        jTFuser2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTFuser2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFuser2MouseClicked(evt);
            }
        });
        jPanel1.add(jTFuser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 230, 40));

        jSeparator11.setBackground(new java.awt.Color(235, 235, 235));
        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 250, 20));

        jTFuser3.setBackground(new java.awt.Color(243, 240, 235));
        jTFuser3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTFuser3.setForeground(new java.awt.Color(102, 102, 102));
        jTFuser3.setText("Inserte nombre");
        jTFuser3.setBorder(null);
        jTFuser3.setCaretColor(new java.awt.Color(204, 51, 0));
        jTFuser3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTFuser3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFuser3MouseClicked(evt);
            }
        });
        jPanel1.add(jTFuser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 230, 40));

        jLabel9.setBackground(new java.awt.Color(235, 235, 235));
        jLabel9.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel9.setText("Pregunta de seguridad");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, 160, 20));

        jPassword.setBackground(new java.awt.Color(243, 240, 235));
        jPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPassword.setForeground(new java.awt.Color(102, 102, 102));
        jPassword.setText("Inserte contraseña");
        jPassword.setBorder(null);
        jPassword.setCaretColor(new java.awt.Color(204, 51, 0));
        jPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordMouseClicked(evt);
            }
        });
        jPanel1.add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 220, 30));

        Ocultar.setBackground(new java.awt.Color(242, 242, 242));
        Ocultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/oculto.png"))); // NOI18N
        Ocultar.setBorder(null);
        Ocultar.setBorderPainted(false);
        Ocultar.setContentAreaFilled(false);
        Ocultar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/ver.png"))); // NOI18N
        Ocultar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/ver.png"))); // NOI18N
        Ocultar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/ver.png"))); // NOI18N
        Ocultar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/ver.png"))); // NOI18N
        Ocultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OcultarActionPerformed(evt);
            }
        });
        jPanel1.add(Ocultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 160, 20, 20));

        jLabel10.setBackground(new java.awt.Color(235, 235, 235));
        jLabel10.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel10.setText("Nombre(s)");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 90, 20));

        jTFuser1.setBackground(new java.awt.Color(243, 240, 235));
        jTFuser1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTFuser1.setForeground(new java.awt.Color(102, 102, 102));
        jTFuser1.setText("inserte respuesta");
        jTFuser1.setBorder(null);
        jTFuser1.setCaretColor(new java.awt.Color(204, 51, 0));
        jTFuser1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTFuser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFuser1MouseClicked(evt);
            }
        });
        jTFuser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFuser1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTFuser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 230, 40));

        jSeparator12.setBackground(new java.awt.Color(235, 235, 235));
        jSeparator12.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, 250, 20));

        jLabel11.setBackground(new java.awt.Color(235, 235, 235));
        jLabel11.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel11.setText("Apellido Paterno");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 130, 20));

        jTFuser4.setBackground(new java.awt.Color(243, 240, 235));
        jTFuser4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTFuser4.setForeground(new java.awt.Color(102, 102, 102));
        jTFuser4.setText("Ingrese A. Paterno");
        jTFuser4.setBorder(null);
        jTFuser4.setCaretColor(new java.awt.Color(204, 51, 0));
        jTFuser4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTFuser4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFuser4MouseClicked(evt);
            }
        });
        jPanel1.add(jTFuser4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 230, 40));

        jSeparator10.setBackground(new java.awt.Color(235, 235, 235));
        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 250, 20));

        jLabel13.setBackground(new java.awt.Color(235, 235, 235));
        jLabel13.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel13.setText("Correo electronico");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 130, 20));

        jTFuser5.setBackground(new java.awt.Color(243, 240, 235));
        jTFuser5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTFuser5.setForeground(new java.awt.Color(102, 102, 102));
        jTFuser5.setText("Inserte un correo electronico");
        jTFuser5.setBorder(null);
        jTFuser5.setCaretColor(new java.awt.Color(204, 51, 0));
        jTFuser5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTFuser5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFuser5MouseClicked(evt);
            }
        });
        jTFuser5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFuser5ActionPerformed(evt);
            }
        });
        jPanel1.add(jTFuser5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 230, 40));

        jSeparator13.setBackground(new java.awt.Color(235, 235, 235));
        jSeparator13.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 250, 20));

        jLabel8.setFont(new java.awt.Font("Microsoft Tai Le", 0, 36)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/Register.png"))); // NOI18N
        jLabel8.setText("Registro");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 340, 80));

        Minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/Minimize.png"))); // NOI18N
        Minimize.setBorder(null);
        Minimize.setBorderPainted(false);
        Minimize.setContentAreaFilled(false);
        Minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Minimize.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/Minimize2.png"))); // NOI18N
        Minimize.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/Minimize2.png"))); // NOI18N
        Minimize.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/Minimize2.png"))); // NOI18N
        Minimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimizeActionPerformed(evt);
            }
        });
        jPanel1.add(Minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, -1, 40));

        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/close.png"))); // NOI18N
        Close.setBorder(null);
        Close.setBorderPainted(false);
        Close.setContentAreaFilled(false);
        Close.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Close.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/close2.png"))); // NOI18N
        Close.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/close2.png"))); // NOI18N
        Close.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGM/close2.png"))); // NOI18N
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });
        jPanel1.add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, -1, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void horarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horarioActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new exa().setVisible(true);
//            }
//        });
//        this.dispose();
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBLimpiarActionPerformed

    private void jTFuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFuserMouseClicked
        // TODO add your handling code here:
        if (jTFuser.getText().equals("Ingrese Usuario")) {
            jTFuser.setText("");
        }
    }//GEN-LAST:event_jTFuserMouseClicked

    private void jTFuser2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFuser2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFuser2MouseClicked

    private void jTFuser3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFuser3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFuser3MouseClicked

    private void jPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordMouseClicked
        // TODO add your handling code here:
        if (jPassword.getText().equals("Inserte contraseña")) {
            jPassword.setText("");
        }
    }//GEN-LAST:event_jPasswordMouseClicked

    private void OcultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OcultarActionPerformed
        if (Ocultar.isSelected()==true) {
            jPassword.setEchoChar((char)0);
        }else{
            jPassword.setEchoChar('•');

        }
    }//GEN-LAST:event_OcultarActionPerformed

    private void jTFuser1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFuser1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFuser1MouseClicked

    private void jTFuser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFuser1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFuser1ActionPerformed

    private void jTFuser4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFuser4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFuser4MouseClicked

    private void jTFuser5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFuser5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFuser5MouseClicked

    private void jTFuser5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFuser5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFuser5ActionPerformed

    private void MinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimizeActionPerformed
        this.setState(LogIn.ICONIFIED);
    }//GEN-LAST:event_MinimizeActionPerformed

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "Desea regresar al inicio?","Exit",dialog);
        if (result==0){
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
        }
        this.dispose();
    }//GEN-LAST:event_CloseActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true); //abrir el FrameHome que es nuestro Menu
            }
        });
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Registro().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Close;
    private javax.swing.JButton Minimize;
    private javax.swing.JToggleButton Ocultar;
    private javax.swing.JButton back;
    private javax.swing.JComboBox<String> horario;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBLimpiar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTFuser;
    private javax.swing.JTextField jTFuser1;
    private javax.swing.JTextField jTFuser2;
    private javax.swing.JTextField jTFuser3;
    private javax.swing.JTextField jTFuser4;
    private javax.swing.JTextField jTFuser5;
    // End of variables declaration//GEN-END:variables
}
